REPO = git@github.com:palladius/pasta

pasta-subtree:
	git remote add remote-github-pasta git@github.com:palladius/pasta
	git subtree add --prefix=pasta-subtree/ remote-github-pasta git@github.com:palladius/pasta subtree-branchname


pull:
	git subtree push-all

